FROM node:20-alpine AS build
WORKDIR /app/frontend-admin
COPY frontend-admin/package*.json ./
RUN npm install
COPY frontend-admin/ ./
RUN npm run build

FROM nginx:1.27-alpine
COPY deploy/nginx-admin.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend-admin/dist /var/www/frontend-admin
